### ISSUE TITLE
How do you use a theme?

### ISSUE THREAD

**Issue by styledev** [agrobbin/highcharts-js-rails#1]
How would one enable a theme for highcharts? If we include it in the asset pipeline then it gets loaded in before Highcharts.js and thus will not work.

**Comment by styledev** [comment]
Actually I guess you can just load it inline via <%= javascript_include_tag "gray" %>

**Comment by agrobbin** [comment]
Use the newest released version, 0.1.8, and add the theme to your application.js file like so:

```
//= require highcharts/themes/dark-blue
```

Make sure to include it after the `//= require highcharts` line. That should include it appropriately.
