### ISSUE TITLE
PlotLines does not work

### ISSUE THREAD

**Issue by jmorra** [agrobbin/highcharts-js-rails#3]
I was struggling a lot to try and display plotLines on graphs and having a ton of trouble.  I eventually figured it out, but I think it could be a systemic problem with Array based options.  A documentation of my problem and solution can be found at http://stackoverflow.com/questions/13281657/using-highcharts-with-rails-not-displaying-plotlines

**Comment by agrobbin** [comment]
I am not able to reproduce this error with the code in your StackOverflow. Here is what I have tested and what it has produced in final JavaScript:

Ruby:

``` ruby
Highcharts.new do |chart|
  chart.chart renderTo: 'chart-test'
  chart.yAxis [{title: 'Y-Axis', min: 0, plotLines: {value: 25}}]
end
```

JavaScript:

``` javascript
$(function(){
  new Highcharts.Chart({"chart":{"renderTo":"chart-test"},"yAxis":[{"title":{"text":"Y-Axis"},"min":0,"plotLines":{"value":25}}]})
});
```
