### ISSUE TITLE
Conflict with highcharts-rails gem

### ISSUE THREAD

**Issue by thoran** [agrobbin/highcharts-js-rails#4]
highcharts-rails gem has a Highcharts module, whereas in this gem it is a class.  Is it possible to make them play nicely?  Perhaps by creating a class Highcharts::Chart as I did in my library which I started, which does likewise with this one.

**Comment by thoran** [comment]
Oh, so it _includes_ high charts.js, making the other gem redundant.  Right...

**Comment by agrobbin** [comment]
Sorry for the delay in response @thoran, yeah the Highcharts JS is included with this gem as well.
