### ISSUE TITLE
Can't handle more than one series

### ISSUE THREAD

**Issue by thoran** [agrobbin/highcharts-js-rails#5]
Given the following, the second will overwrite the first...  

chart.series(name: 'foo', ...)
chart.series(name: 'bar', ...)

Highcharts allows for the provision of multiple series, but this Ruby interface doesn't.  I'm guessing you didn't need that?  

While I am working on a fix which adds an array to Highcharts::Series, and requires a change to the Highcharts class to handle series differently, if you get to it first however...

**Comment by agrobbin** [comment]
You can add more than one series by passing it an array:

``` ruby
chart.series [{name: 'foo', data: {...}}, {name: 'bar', data: {...}}]
```

**Comment by thoran** [comment]
Thanks for the prompt response, this time and last.
